# Exception 2

## Оператор throw
Появление exception-ов при выполнение программы связанно с какими то исключительными ситуациями, например: попытка делить на ноль, попутка вызвать метод у null-объекта, попытка прочитать отсутствующий файл и т.д. Во всех этих случаях *исключение* генерирует Java. Но ваш код тоже может  сгенерировать  исключение или, как еще говорят может *«бросить exception»*. Для этого используется команда `throw`
~~~java
public static double division(int a, int b) {
        if (b==0) throw new IllegalArgumentException("b can't be 0!");
        return (double)a/b;
    }
~~~
в этом примере метод division бросает исключение `IllegalArgumentException` в случае, если делитель развен 0
В качестве аргумента для команды throw может использоватьься любой объект, наследник класса Exception  

## Возникновение обработка exception. Поток выполнения программы.
*Нормальный поток выполнения программы* – последовательность выполнения программы в случае отсутствия исключительных ситуаций. 
Если во время выполнения метода случился Exception, *нормальный поток выполнения программы* немедленно прерывается. Это происходит вне зависимости от того, какой это  Exception, бросил ли его системный код JVM или наш код, что послужило причиной… В любом случае,    *нормальный поток выполнения программы* прерывается для обработки exception-а.  
 Exception может быть пойман и обработан ( см. try….catch) непосредственно в месте возникновения. Если Exception остался необработанным, система *выкидывает* его на уровень выше, т.е. прерывает выполнение текущего метода, возвращается в вызвавший его метод и ожидает обработки exception уже в нем. Если этого не происходит, процесс повторяется, система «выбрасывает» необработанный exception уровнем выше и т.д. Если и метод main() не обработал исключение, то exception выкидывается в JVM и обрабатывается системным обработчиком.  Этот процесс называется *«всплытие exception-ов»*. Важно понимать, что если в программе случился Exception (любой, неважно какой!),  он прерывает «нормальный поток выполнения» до момента обработки, при этом он должен и будет обработан в любом случае.
Концептуально Exception это способ прервать выполнение метода и вернуть информацию о проблеме и предпринять какие то действия если нормальное выполнение метода невозможно из за какой то исключительной ситуации. 